# Generated by Django 4.2.3 on 2023-07-04 20:03
"""This suggests that there is a previous migration named 0001_initial in the base app."""
from django.db import migrations, models

"""The migration contains an operations list, which specifies the database operations to be executed as part of this migration."""
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                """The id field is an automatically incrementing primary key, similar to the previous """
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                """The name field is a character field with a maximum length of 200 characters. 
                It is likely intended to store the name of the company."""
                ('name', models.CharField(max_length=200)),
                """The bio field is a character field with a maximum length of 250 characters. 
                It allows for a short bio or description of the company. It can be blank (empty) and nullable (null)."""
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
